@url = http://localhost:8080/api

GET {{url}} HTTP/1.1


###

GET {{url}}/artist HTTP/1.1
// Above gets all artists

###

GET {{url}}/artist/2 HTTP/1.1

###

POST {{url}}/artist/ HTTP/1.1
Content-Type: application/json

{
    "artistId": 0,
    "artistName": "Iron Maiden",
    "artistFollowers": 8582412,
    "artistPopularity": 71,
    "artistSpotifyId": "6mdiAmATAx73kdxrNrnlao"
}

###
PUT {{url}}/artist/2 HTTP/1.1
Content-Type: application/json

{
    "artistId": 2,
    "artistName": "David Bowie",
    "artistSpotifyId": "0oSGxfWSnnOXhD2fKuz2Gy",
    "artistArtFilename": "https://i.scdn.co/image/ab6761610000e5ebb78f77c5583ae99472dd4a49",
    "artistMbid": "5441c29d-3602-4898-b1a1-b77fa23b8e50"
}

###

DELETE {{url}}/artist/14 HTTP/1.1

###

GET {{url}}/artists/2 HTTP/1.1

###