@url = http://musicbrainz.org/ws/2

GET {{url}} HTTP/1.1

###

GET {{url}}/artist HTTP/1.1

###

GET {{url}}/artist/5182c1d9-c7d2-4dad-afa0-ccfeada921a8 HTTP/1.1
// Gets Black Sabbath in XML

###

GET {{url}}/artist/5182c1d9-c7d2-4dad-afa0-ccfeada921a8?inc=release-groups&fmt=json HTTP/1.1

// Gets Black Sabbath release groups

###

POST {{url}}/agent/ HTTP/1.1
Content-Type: application/json

{
    "artistId": 0,
    "artistMBID": 0,
    "artistSpotifyId": 0,
    "artistName": "Farty McStinkface"
}

###

PUT {{url}}/agent/2 HTTP/1.1
Content-Type: application/json

{
    "artistId": 2,
    "artistName": "Stinky McFartface"
}

###

DELETE {{url}}/agent/1 HTTP/1.1