@url = https://api.spotify.com/v1


###

GET {{url}}/artist/5M52tdBnJaKSvOpJGz8mfZ HTTP/1.1
Authorization: Bearer 
// Gets Black Sabbath from Spotify

###

GET {{url}}/artists/5M52tdBnJaKSvOpJGz8mfZ HTTP/1.1

// Gets Black Sabbath release groups

###

GET {{url}}/artists/5M52tdBnJaKSvOpJGz8mfZ/albums?include_groups=album&limit=40&market=US HTTP/1.1
###
